### ISSUE TITLE
Grafana Dashboards

### ISSUE THREAD

**Issue by GabrielT247** [OpenBMP/obmp-psql#8]
Tim,

Let me start by saying I love the work you've done here. BMP is a really cool protocol and your OpenBMP implementation is a great tool to monitor BGP information. My team and I had followed your guide on https://www.openbmp.org/ to get OpenBMP set up and it is working fine. I was wondering however you had any information regarding getting the Grafana dashboards set up. I am working in a small/medium size ISP and there are a couple of things that I want to add to some of the dashboards to make them a bit more useful. 

I appreciate your work on OpenBMP and I am having a great time learning how everything is set up.

Thanks,
Gabriel Terry

**Comment by TimEvens** [comment]
@GabrielT247, thank you, that sounds great.  

The OBMP public provisioned dashboards are intended to be replaced/updated based on the [OBMP-Grafana Repo](https://github.com/OpenBMP/obmp-grafana) using [grafana provisioning](https://grafana.com/docs/grafana/latest/administration/provisioning/). You can contribute/update them by updating them locally first and then submit the JSON files via a Pull Request to https://github.com/OpenBMP/obmp-grafana.  The OBMP dashboards are in their own folders (e.g., ```OBMP-*```) so that you can clone them to your own folder for any changes you want to do. Basically use the OBMP ones as templates/starting points.  You'll need to backup yours and redeploy them if you wipe out the grafana volume.   OBMP folder dashboards are intended to be replaced/updated on upgrade.  For example, there have been some fixes and some new updates that will update those ```OBMP-*``` dashboards.    If you made changes to those, they would be overwritten.  

If you have updates that others would like too, it would be excellent if you could do a PR to [OBMP-Grafana Repo](https://github.com/OpenBMP/obmp-grafana) to share those.  You can add new dashboards or update existing ones.
